### ISSUE TITLE
TRANSACTION_CLOSED error for writes to replica db

### ISSUE THREAD

**Issue by rlfrahm** [ruheni/fullstack-prisma-turso-embedded-db#2]
Hey there! Trying to implement embedded replica's via `syncUrl` and the `app/lib/prisma.ts` config you have and for all writes to the db (`await prisma.model.create`) I'm receiving the error:

```
TRANSACTION_CLOSED: The transaction is closed [...]

...
```

Do you happen to know where I've misconfigured something? I've copy-pasta'd your `prisma.ts` file as well as experimented to various uses of `sync()` to no avail.

Thanks! 😀

**Comment by ruheni** [comment]
👋

Apologies for the slow response. This seems to be a bug on libSQL and is currently being tracked here: https://github.com/prisma/prisma/discussions/21345#discussioncomment-7479578 😄

**Comment by rlfrahm** [comment]
Yes we are working through a fix here https://github.com/libsql/libsql-client-ts/issues/124
